"""Browser-based API client — uses patchright to make requests from a real browser context.

stoken is generated by the browser's JS environment automatically, eliminating expiration issues.
Used for high-risk operations: search, recommend, greet, batch-greet.

Supports two modes:
  1. CDP mode (preferred): connects to user's existing Chrome via DevTools Protocol
  2. Patchright mode (fallback): launches a headless Chromium instance
"""
import sys
from pathlib import Path

from patchright.sync_api import sync_playwright

from boss_agent_cli.api import endpoints
from boss_agent_cli.api.throttle import RequestThrottle

HOME_URL = "https://www.zhipin.com/"
CDP_DEFAULT_URL = "http://localhost:9222"

# 超时常量
_CDP_PROBE_TIMEOUT = 3           # CDP 探测 HTTP 超时（秒）
_NAV_TIMEOUT_MS = 15000          # 页面导航超时（毫秒）

# macOS / Linux / Windows Chrome user data 默认路径
_CHROME_USER_DATA_CANDIDATES = [
	Path.home() / "Library/Application Support/Google/Chrome",              # macOS
	Path.home() / ".config/google-chrome",                                  # Linux
	Path.home() / "AppData/Local/Google/Chrome/User Data",                  # Windows
]


class BrowserSession:
	"""Persistent browser session that makes API calls via page.evaluate(fetch).

	Tries CDP connection to user's Chrome first; falls back to headless patchright.
	"""

	def __init__(self, cookies: dict, user_agent: str, *, delay: tuple[float, float] = (1.5, 3.0), cdp_url: str | None = None, logger=None):
		self._throttle = RequestThrottle(delay)
		self._pw = None
		self._browser = None
		self._context = None
		self._page = None
		self._cookies = cookies
		self._user_agent = user_agent
		self._started = False
		self._cdp_url = cdp_url
		self._is_cdp = False
		self._own_context = False  # 是否由我们创建的 context（需要在 close 时清理）
		self._logger = logger
		self._bridge_client = None
		self._is_bridge = False

	def _log(self, message: str) -> None:
		"""通过注入的 logger 输出，受 --log-level 控制。"""
		if self._logger:
			self._logger.info(message)
		else:
			print(message, file=sys.stderr)

	def _ensure_started(self):
		if self._started:
			return

		# 优先尝试 Bridge 模式（Chrome 扩展 + daemon，零配置）
		if self._try_bridge():
			return

		self._pw = sync_playwright().start()

		# 第二优先：CDP 连接用户 Chrome（真实指纹 + 天然登录态）
		if self._try_cdp():
			return

		# 兜底：启动 headless patchright
		self._start_headless()

	def _try_bridge(self) -> bool:
		"""尝试通过 Browser Bridge（Chrome 扩展 + daemon）连接。"""
		try:
			from boss_agent_cli.bridge.client import BridgeClient
			client = BridgeClient()
			if not client.is_running():
				return False
			if not client.is_extension_connected():
				self._log("[boss] Bridge daemon 运行中但扩展未连接")
				return False
			self._bridge_client = client
			self._started = True
			self._is_cdp = False
			self._is_bridge = True
			self._log("[boss] Bridge 模式连接成功（Chrome 扩展 + daemon）")
			return True
		except Exception:
			return False

	def _try_cdp(self) -> bool:
		"""Try connecting to user's Chrome via CDP.

		Attempts in order:
		  1. Explicit cdp_url if provided
		  2. Default http://localhost:9222 (+ auto WS fallback)
		  3. WebSocket URL from Chrome's DevToolsActivePort file
		"""
		urls_to_try = []
		if self._cdp_url:
			urls_to_try.append(self._cdp_url)
		urls_to_try.append(CDP_DEFAULT_URL)

		# 从 DevToolsActivePort 文件读取 WebSocket URL
		ws_url = self._read_devtools_active_port()
		if ws_url:
			urls_to_try.append(ws_url)

		for url in urls_to_try:
			if self._try_connect(url):
				return True
			# HTTP URL 连接失败时，尝试从 /json/version 获取 WS URL
			if url.startswith("http"):
				ws = self._fetch_ws_url(url)
				if ws and self._try_connect(ws):
					return True
		return False

	def _try_connect(self, url: str) -> bool:
		"""Attempt a single CDP connection, reusing user's existing context.

		Reuses the first existing browser context (preserves login state and
		avoids Chrome's automation detection on new contexts). Only creates
		a new context when none exists.
		"""
		try:
			self._browser = self._pw.chromium.connect_over_cdp(url)
			contexts = self._browser.contexts

			if contexts:
				# 复用用户现有 context（保留登录态 + 规避 automation 检测）
				self._context = contexts[0]
				self._own_context = False  # 非我们创建，close 时不关闭
			else:
				# 没有已存在 context，创建新的并注入 cookies
				self._context = self._browser.new_context()
				if self._cookies:
					self._context.add_cookies([
						{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
						for name, value in self._cookies.items()
					])
				self._own_context = True

			self._page = self._context.new_page()
			# CDP 模式下用较长超时 + commit 级等待（避免 networkidle 卡住）
			try:
				self._page.goto(HOME_URL, wait_until="commit", timeout=_NAV_TIMEOUT_MS)
			except Exception:
				pass  # 即使导航超时，页面 JS 环境已可用
			self._started = True
			self._is_cdp = True
			reuse_label = "复用用户 context" if not self._own_context else "新建 context"
			self._log(f"[boss] CDP 连接成功 ({url})，{reuse_label}")
			return True
		except Exception:
			if self._browser:
				try:
					self._browser.close()
				except Exception:
					pass
				self._browser = None
			return False

	@staticmethod
	def _fetch_ws_url(http_url: str) -> str | None:
		"""Fetch WebSocket debugger URL from Chrome's /json/version endpoint."""
		import httpx
		try:
			resp = httpx.get(f"{http_url}/json/version", timeout=_CDP_PROBE_TIMEOUT)
			return resp.json().get("webSocketDebuggerUrl")
		except Exception:
			return None

	@staticmethod
	def _read_devtools_active_port() -> str | None:
		"""Read Chrome's DevToolsActivePort file to get WS endpoint."""
		for user_data_dir in _CHROME_USER_DATA_CANDIDATES:
			port_file = user_data_dir / "DevToolsActivePort"
			if port_file.exists():
				try:
					lines = port_file.read_text().strip().splitlines()
					if len(lines) >= 2:
						port = lines[0].strip()
						ws_path = lines[1].strip()
						return f"ws://127.0.0.1:{port}{ws_path}"
				except Exception:
					continue
		return None

	def _start_headless(self):
		"""Fallback: launch headless patchright Chromium."""
		self._browser = self._pw.chromium.launch(headless=True)
		self._context = self._browser.new_context(
			user_agent=self._user_agent,
			viewport={"width": 1280, "height": 800},
			locale="zh-CN",
			timezone_id="Asia/Shanghai",
		)
		self._own_context = True
		self._context.add_cookies([
			{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
			for name, value in self._cookies.items()
		])
		self._page = self._context.new_page()
		self._page.goto(HOME_URL, wait_until="domcontentloaded")
		self._page.wait_for_load_state("networkidle")
		self._started = True
		self._is_cdp = False
		self._log("[boss] CDP 不可用（提示：需以 --remote-debugging-port=9222 启动 Chrome），降级到 headless patchright")

	# ── Core request via browser fetch() ─────────────────────────────

	def request(self, method: str, url: str, *, params: dict | None = None, data: dict | None = None) -> dict:
		self._ensure_started()
		self._throttle.wait()

		referer = endpoints.REFERER_MAP.get(url, f"{endpoints.BASE_URL}/")

		# Bridge 模式：通过扩展 fetch
		if self._is_bridge and self._bridge_client:
			import urllib.parse
			full_url = url
			if params:
				full_url = f"{url}?{urllib.parse.urlencode(params)}"
			result = self._bridge_client.fetch_json(
				full_url,
				method=method,
				data=data,
				referer=referer,
			)
			self._throttle.mark()
			return result

		# Playwright 模式（CDP 或 headless）
		result = self._page.evaluate("""
			async ({method, url, params, data, referer}) => {
				try {
					let fetchUrl = url;
					if (params && Object.keys(params).length > 0) {
						const sp = new URLSearchParams();
						for (const [k, v] of Object.entries(params)) {
							if (v !== null && v !== undefined) sp.append(k, String(v));
						}
						fetchUrl = url + '?' + sp.toString();
					}

					const options = {
						method: method,
						credentials: 'include',
						headers: {
							'Accept': 'application/json, text/plain, */*',
							'Referer': referer,
							'X-Requested-With': 'XMLHttpRequest',
						},
					};

					if (method === 'POST' && data) {
						options.headers['Content-Type'] = 'application/x-www-form-urlencoded';
						const formData = new URLSearchParams();
						for (const [k, v] of Object.entries(data)) {
							formData.append(k, String(v));
						}
						options.body = formData.toString();
					}

					const resp = await fetch(fetchUrl, options);
					return await resp.json();
				} catch (e) {
					return {code: -1, message: e.message, zpData: {}};
				}
			}
		""", {"method": method, "url": url, "params": params or {}, "data": data, "referer": referer})

		self._throttle.mark()
		return result

	# ── Lifecycle ────────────────────────────────────────────────────

	@property
	def is_cdp(self) -> bool:
		"""Whether this session is using CDP connection to user's Chrome."""
		return self._is_cdp

	def close(self):
		if self._is_bridge and self._bridge_client:
			try:
				self._bridge_client.close_window()
			except Exception:
				pass
			self._bridge_client = None
			self._started = False
			return

		if self._is_cdp:
			# CDP 模式：关闭我们创建的 page 和 context，不关闭用户浏览器
			if self._page:
				try:
					self._page.close()
				except Exception:
					pass
			if self._own_context and self._context:
				try:
					self._context.close()
				except Exception:
					pass
		else:
			# Headless 模式：关闭整个浏览器实例
			if self._browser:
				self._browser.close()
		if self._pw:
			self._pw.stop()
		self._started = False

	def __enter__(self):
		return self

	def __exit__(self, *args):
		self.close()
